"use client";

import { type FormEvent, type ReactNode, useState } from "react";
import type { DemoResponse } from "@/lib/precall";

const FORM_FIELDS = [
  {
    key: "company",
    label: "Company or contact",
    placeholder: "Northwind Cycles",
    multiline: false,
  },
  {
    key: "projectSummary",
    label: "Project summary",
    placeholder: "We need to replace our spreadsheet-based workshop bookings.",
    multiline: true,
  },
  {
    key: "goals",
    label: "Goals for the call",
    placeholder: "Agree a realistic first phase and who signs it off.",
    multiline: true,
  },
  {
    key: "budget",
    label: "Budget range",
    placeholder: "Not decided yet",
    multiline: false,
  },
  {
    key: "timeline",
    label: "Desired timeline",
    placeholder: "Before the spring season",
    multiline: false,
  },
  {
    key: "contactEmail",
    label: "Contact email",
    placeholder: "ops@northwind.example",
    multiline: false,
  },
  {
    key: "internalNotes",
    label: "Internal note (kept out of the professional brief)",
    placeholder: "A local agency already quoted them a fixed price.",
    multiline: true,
  },
] as const;

const INITIAL_VALUES: Record<string, string> = {
  company: "Northwind Cycles",
  projectSummary:
    "We run a bike workshop and want to replace our spreadsheet-based service bookings with something customers can use directly.",
  goals: "Agree on a realistic first phase and understand what it would take to get there.",
  budget: "",
  timeline: "",
  contactEmail: "ops@northwind.example",
  internalNotes: "They mentioned that a local agency already quoted them a fixed price.",
};

function displayValue(value: unknown): string {
  if (typeof value === "string") return value;
  if (value === null || value === undefined) return "";
  return JSON.stringify(value);
}

function readErrorMessage(payload: unknown): string {
  if (typeof payload === "object" && payload !== null && "error" in payload) {
    const message = (payload as { error: unknown }).error;
    if (typeof message === "string") return message;
  }
  return "The submission was rejected.";
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div>
      <h3>{title}</h3>
      {children}
    </div>
  );
}

function Brief({ response }: { response: DemoResponse }) {
  const { analysis, aiInputKeys, fields, delivery, professionalAttachment } = response;

  return (
    <>
      <section className="card">
        <h2>Internal pre-call brief</h2>
        <p className="notice">
          AI prepares the human. This is not a quotation, an estimate, a scope commitment, or a
          deadline.
        </p>
        <p className="muted">
          Generated by a deterministic local adapter. No AI provider was called and no email left
          this process.
        </p>

        {analysis.status === "succeeded" ? (
          <>
            <p>{analysis.result.summary}</p>
            <dl>
              <dt>Clarity</dt>
              <dd>
                {analysis.result.clarity.level} — {analysis.result.clarity.reason}
              </dd>
              <dt>Confidence</dt>
              <dd>
                {analysis.result.confidence.level} — {analysis.result.confidence.reason}
              </dd>
            </dl>

            {analysis.result.facts.length > 0 && (
              <Section title="Facts stated by the client">
                <ul>
                  {analysis.result.facts.map((fact) => (
                    <li key={fact.text}>
                      {fact.text}
                      <div className="chips">
                        {fact.sourceFieldKeys.map((key) => (
                          <span className="chip" key={key}>
                            from {key}
                          </span>
                        ))}
                      </div>
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {analysis.result.inferences.length > 0 && (
              <Section title="Inferences">
                <ul>
                  {analysis.result.inferences.map((inference) => (
                    <li key={inference.text}>
                      {inference.text}
                      <div className="chips">
                        <span className="chip">{inference.confidence} confidence</span>
                        {inference.basedOnFieldKeys.map((key) => (
                          <span className="chip" key={key}>
                            based on {key}
                          </span>
                        ))}
                      </div>
                      <p className="muted">{inference.reason}</p>
                      {inference.needsValidation !== undefined && (
                        <p className="muted">Validate: {inference.needsValidation}</p>
                      )}
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {analysis.result.assumptions.length > 0 && (
              <Section title="Assumptions">
                <ul>
                  {analysis.result.assumptions.map((assumption) => (
                    <li key={assumption.text}>
                      {assumption.text}
                      {assumption.impact !== undefined && (
                        <div className="chips">
                          <span className="chip">{assumption.impact} impact</span>
                        </div>
                      )}
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {analysis.result.unknowns.length > 0 && (
              <Section title="Unknowns">
                <ul>
                  {analysis.result.unknowns.map((unknown) => (
                    <li key={unknown.text}>
                      {unknown.text}
                      <div className="chips">
                        <span className="chip chip-internal">{unknown.priority}</span>
                      </div>
                      <p className="muted">{unknown.whyItMatters}</p>
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {analysis.result.risks.length > 0 && (
              <Section title="Risks">
                <ul>
                  {analysis.result.risks.map((risk) => (
                    <li key={risk.text}>
                      {risk.text}
                      <div className="chips">
                        {risk.severity !== undefined && (
                          <span className="chip chip-internal">{risk.severity} severity</span>
                        )}
                      </div>
                      <p className="muted">{risk.reason}</p>
                      {risk.needsValidation !== undefined && (
                        <p className="muted">Validate: {risk.needsValidation}</p>
                      )}
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            {analysis.result.discoveryQuestions.length > 0 && (
              <Section title="Discovery questions">
                <ul>
                  {analysis.result.discoveryQuestions.map((question) => (
                    <li key={question.question}>
                      {question.question}
                      <div className="chips">
                        <span className="chip">{question.priority}</span>
                      </div>
                      <p className="muted">{question.reason}</p>
                    </li>
                  ))}
                </ul>
              </Section>
            )}

            <Section title="Preliminary roadmap">
              <div className="chips">
                <span className="chip">{analysis.result.roadmap.status}</span>
              </div>
              {analysis.result.roadmap.note !== undefined && (
                <p className="muted">{analysis.result.roadmap.note}</p>
              )}
              <ul>
                {analysis.result.roadmap.phases.map((phase) => (
                  <li key={phase.name}>
                    {phase.name}
                    <p className="muted">{phase.purpose}</p>
                  </li>
                ))}
              </ul>
            </Section>
          </>
        ) : (
          <p className="warn">
            AI analysis unavailable ({analysis.reason}). The inquiry below is preserved, and the
            delivery attempt still ran.
          </p>
        )}
      </section>

      <section className="card">
        <h2>Field policy and what crossed each boundary</h2>
        <table>
          <thead>
            <tr>
              <th>Field</th>
              <th>Submitted value</th>
              <th>Boundaries</th>
            </tr>
          </thead>
          <tbody>
            {fields.map((field) => (
              <tr key={field.key}>
                <td>{field.label}</td>
                <td>{displayValue(field.value)}</td>
                <td>
                  <div className="chips">
                    <span className={field.sendToAI ? "chip chip-ai" : "chip"}>
                      {field.sendToAI ? "sent to AI" : "withheld from AI"}
                    </span>
                    <span className={field.includeInOutput ? "chip" : "chip chip-internal"}>
                      {field.includeInOutput ? "in professional brief" : "internal only"}
                    </span>
                    {field.sensitive && <span className="chip">sensitive</span>}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="muted">
          Fields the adapter received: {aiInputKeys.length === 0 ? "none" : aiInputKeys.join(", ")}.
        </p>
      </section>

      <section className="card">
        <h2>Delivery (simulated)</h2>
        <dl>
          <dt>Outcome</dt>
          <dd>
            {delivery.outcome.status === "sent" ? "sent" : `failed (${delivery.outcome.reason})`}
          </dd>
          <dt>Trusted recipient</dt>
          <dd>{delivery.recipient}</dd>
          <dt>Subject</dt>
          <dd>{delivery.subject}</dd>
          <dt>Attachments</dt>
          <dd>
            {delivery.attachmentFilenames.length === 0
              ? "none"
              : delivery.attachmentFilenames.join(", ")}
          </dd>
        </dl>
        <p className="muted">
          The example transport reports success and sends nothing. The recipient comes from server
          configuration, never from the submitted form.
        </p>
        {professionalAttachment !== undefined && (
          <>
            <h3>
              {professionalAttachment.filename} ({professionalAttachment.contentType})
            </h3>
            <p className="muted">
              Built only from fields with output permission, so the internal note is absent here.
            </p>
            <pre>{professionalAttachment.content}</pre>
          </>
        )}
      </section>

      <footer>
        Framework-specific code lives in this example application, not in the PreCall core. See the
        example README and the PreCall repository for the library boundaries.
      </footer>
    </>
  );
}

export default function Home() {
  const [values, setValues] = useState<Record<string, string>>(INITIAL_VALUES);
  const [response, setResponse] = useState<DemoResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setPending(true);
    setError(null);

    try {
      const result = await fetch("/api/precall", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(values),
      });
      const payload: unknown = await result.json();
      if (!result.ok) {
        setResponse(null);
        setError(readErrorMessage(payload));
        return;
      }
      setResponse(payload as DemoResponse);
    } catch {
      setResponse(null);
      setError("The request could not be completed.");
    } finally {
      setPending(false);
    }
  }

  return (
    <main>
      <header>
        <h1>PreCall · Next.js integration example</h1>
        <p className="lede">
          One Route Handler, one form, and the public <code>precall</code> package. The browser
          submits a structured inquiry and the server turns it into an internal pre-call brief.
        </p>
      </header>

      <section className="card">
        <h2>Client inquiry</h2>
        <form onSubmit={handleSubmit}>
          {FORM_FIELDS.map((field) => (
            <div key={field.key}>
              <label htmlFor={field.key}>{field.label}</label>
              {field.multiline ? (
                <textarea
                  id={field.key}
                  placeholder={field.placeholder}
                  value={values[field.key] ?? ""}
                  onChange={(event) =>
                    setValues((current) => ({ ...current, [field.key]: event.target.value }))
                  }
                />
              ) : (
                <input
                  id={field.key}
                  placeholder={field.placeholder}
                  value={values[field.key] ?? ""}
                  onChange={(event) =>
                    setValues((current) => ({ ...current, [field.key]: event.target.value }))
                  }
                />
              )}
            </div>
          ))}
          <button type="submit" disabled={pending}>
            {pending ? "Preparing…" : "Prepare pre-call brief"}
          </button>
        </form>
        <p className="muted">
          Leave the budget and timeline empty to see missing information become unknowns, risks, and
          discovery questions. Submitting only the contact email shows the fallback used when no
          permitted field reaches AI.
        </p>
      </section>

      {error !== null && (
        <section className="card">
          <p className="error">{error}</p>
        </section>
      )}

      {response !== null && <Brief response={response} />}
    </main>
  );
}
